# -*- coding: UTF-8 -*-

from Products.CMFCore.permissions import setDefaultRoles

import os


PROJECTNAME = "cedes"
DEFAULT_ADD_CONTENT_PERMISSION = "Add CedesResources"

CEDES_RESOURCE_TYPES = ('ArticleGratuit',
                        'ArticlePayant',
                        'SiteInternet',
                        'Statistiques',
                        'Audio',
                        'Video',
                        'Cederom',
                        'Bibliographie',
                        'SequenceApprentissage')

CEDES_DS_KW_PREFIX = "ds-kw-"

EXTRA_MAIL_TO = ['cedes@unamur.be', 'log@goforweb.be']
setDefaultRoles(DEFAULT_ADD_CONTENT_PERMISSION, ('Manager', 'Owner',))

# DEFAULT_PRESSBANKING_ID = '55634' # id compte go4web
# DEFAULT_PRESSBANKING_ID = '11968' # id compte toumson
DEFAULT_PRESSBANKING_ID = '36981'  # id compte webinconcept

PRINT_SOAP_REQUEST = False
FOLDER_TO_PRINT = ''
ARTICLE_TO_PRINT = ''
PRINT_LIMIT = 10000

PB_MAX_ART_BY_FOLDER = 150
PB_PATH = os.path.join(os.environ['INSTANCE_HOME'], 'var', 'pressbanking')
XML_FILE_PATH = os.path.join(PB_PATH, "metadatas.xml")
BACKUP_PB_PATH = os.path.join(PB_PATH, 'backups')
DO_PB_BACKUP = True

COUNTRIES = [
    ["AF", "Afghanistan"],
    ["ZA", "Afrique du Sud"],
    ["AL", "Albanie"],
    ["DZ", "Algérie"],
    ["DE", "Allemagne"],
    ["AD", "Andorre"],
    ["AO", "Angola"],
    ["AI", "Anguilla"],
    ["AQ", "Antarctique"],
    ["AG", "Antigua et Barbuda"],
    ["AN", "Antilles Néerlandaises"],
    ["SA", "Arabie Saoudite"],
    ["AR", "Argentine"],
    ["AM", "Arménie"],
    ["AW", "Aruba"],
    ["AU", "Australie"],
    ["AT", "Autriche"],
    ["AZ", "Azerbaïjan"],
    ["BS", "Bahamas"],
    ["BH", "Bahrein"],
    ["BD", "Bangladesh"],
    ["BB", "Barbade"],
    ["BY", "Bélarus"],
    ["BE", "Belgique"],
    ["BZ", "Belize"],
    ["BJ", "Bénin"],
    ["BM", "Bermudes"],
    ["BT", "Bhoutan"],
    ["BO", "Bolivie"],
    ["BA", "Bosnie-Herzégovine"],
    ["BW", "Botswana"],
    ["BR", "Brésil"],
    ["BN", "Brunéi Darussalam"],
    ["BG", "Bulgarie"],
    ["BF", "Burkina Faso"],
    ["BI", "Burundi"],
    ["KH", "Cambodge"],
    ["CM", "Cameroun"],
    ["CA", "Canada"],
    ["CV", "Cap-Vert"],
    ["CL", "Chili"],
    ["CN", "Chine"],
    ["CY", "Chypre"],
    ["CO", "Colombie"],
    ["KM", "Comores"],
    ["CG", "Congo"],
    ["CD", "Congo, République Démocratique"],
    ["KP", "Corée du Nord"],
    ["KR", "Corée du Sud"],
    ["CR", "Costa Rica"],
    ["CI", "Côte D'Ivoire"],
    ["HR", "Croatie"],
    ["CU", "Cuba"],
    ["DK", "Danemark"],
    ["DJ", "Djibouti"],
    ["DM", "Dominique"],
    ["EG", "Egypte"],
    ["SV", "El Salvador"],
    ["AE", "Emirats Arabes Unis"],
    ["EC", "Equateur"],
    ["GQ", "Equatorial Guinée Equatoriale"],
    ["ER", "Erythrée"],
    ["ES", "Espagne"],
    ["EE", "Estonie"],
    ["US", "Etats-Unis"],
    ["ET", "Ethiopie"],
    ["FJ", "Fidji"],
    ["FI", "Finlande"],
    ["FR", "France"],
    ["GA", "Gabon"],
    ["GM", "Gambie"],
    ["GE", "Géorgie"],
    ["GS", "Géorgie du Sud et Iles Sandwich  du Sud"],
    ["GH", "Ghana"],
    ["GI", "Gibraltar"],
    ["GR", "Grèce"],
    ["GD", "Grenade"],
    ["GL", "Groenland"],
    ["GP", "Guadeloupe"],
    ["GU", "Guam"],
    ["GT", "Guatemala"],
    ["GG", "Guernesey"],
    ["GN", "Guinée"],
    ["GW", "Guinée-Bissau"],
    ["GY", "Guyana"],
    ["GF", "Guyane Française"],
    ["HT", "Haiti"],
    ["HN", "Honduras"],
    ["HK", "Hong Kong"],
    ["HU", "Hongrie"],
    ["BV", "Ile Bouvet"],
    ["CX", "Ile Christmas"],
    ["IM", "Ile de Man"],
    ["NF", "Ile Norfolk"],
    ["AX", "Iles Aland"],
    ["KY", "Iles Caïmanes"],
    ["CC", "Iles Cocos (Keeling)"],
    ["CK", "Iles Cook"],
    ["FK", "Iles Falkland (Malvinas)"],
    ["FO", "Iles Féroé"],
    ["HM", "Iles Heard and McDonald"],
    ["MP", "Iles Mariannes du Nord"],
    ["MH", "Iles Marshall"],
    ["UM", "Iles Mineures Eloignées des Etats-Unis"],
    ["SB", "Iles Salomon"],
    ["TC", "Iles Turks et Caïques"],
    ["VG", "Iles Vierges Britanniques"],
    ["VI", "Iles Vierges des Etats-Unis"],
    ["IN", "Inde"],
    ["ID", "Indonésie"],
    ["IR", "Iran"],
    ["IQ", "Iraq"],
    ["IE", "Irlande"],
    ["IS", "Islande"],
    ["IL", "Israël"],
    ["IT", "Italie"],
    ["JM", "Jamaïque"],
    ["JP", "Japon"],
    ["JE", "Jersey"],
    ["JO", "Jordanie"],
    ["KZ", "Kazakhstan"],
    ["KE", "Kenya"],
    ["KG", "Kirghizistan"],
    ["KI", "Kiribati"],
    ["KW", "Koweit"],
    ["LA", "Laos"],
    ["LS", "Lesotho"],
    ["LV", "Lettonie"],
    ["LB", "Liban"],
    ["LR", "Libéria"],
    ["LY", "Libye"],
    ["LI", "Liechtenstein"],
    ["LT", "Lituanie"],
    ["LU", "Luxembourg"],
    ["MO", "Macao"],
    ["MK", "Macédoine"],
    ["MG", "Madagascar"],
    ["MY", "Malaisie"],
    ["MW", "Malawi"],
    ["MV", "Maldives"],
    ["ML", "Mali"],
    ["MT", "Malte"],
    ["MA", "Maroc"],
    ["MQ", "Martinique"],
    ["MU", "Maurice"],
    ["MR", "Mauritanie"],
    ["YT", "Mayotte"],
    ["MX", "Mexique"],
    ["FM", "Micronésie"],
    ["MD", "Moldova"],
    ["MC", "Monaco"],
    ["MN", "Mongolie"],
    ["ME", "Monténégro"],
    ["MS", "Montserrat"],
    ["MZ", "Mozambique"],
    ["MM", "Myanmar"],
    ["NA", "Namibie"],
    ["NR", "Nauru"],
    ["NP", "Népal"],
    ["NI", "Nicaragua"],
    ["NE", "Niger"],
    ["NG", "Nigéria"],
    ["NU", "Niué"],
    ["NO", "Norvège"],
    ["NZ", "Nouvelle Zélande"],
    ["NC", "Nouvelle-Calédonie"],
    ["IO", "Océan Indien, Territoire Britannique de l'"],
    ["OM", "Oman"],
    ["UG", "Ouganda"],
    ["UZ", "Ouzbékistan"],
    ["PK", "Pakistan"],
    ["PW", "Palaos"],
    ["PA", "Panama"],
    ["PG", "Papouasie Nouvelle Guinée"],
    ["PY", "Paraguay"],
    ["NL", "Pays-Bas"],
    ["PE", "Pérou"],
    ["PH", "Philippines"],
    ["PN", "Pitcairn"],
    ["PL", "Pologne"],
    ["PF", "Polynésie Française"],
    ["PR", "Porto Rico"],
    ["PT", "Portugal"],
    ["QA", "Qatar"],
    ["CF", "République Centrafricaine"],
    ["DO", "République Dominicaine"],
    ["CZ", "République Tchèque"],
    ["RE", "Réunion"],
    ["RO", "Roumanie"],
    ["GB", "Royaume-Uni"],
    ["RU", "Russie, Fédération de"],
    ["RW", "Rwanda"],
    ["EH", "Sahara Occidental"],
    ["KN", "Saint Kitts et Nevis"],
    ["SM", "Saint Marin"],
    ["VC", "Saint Vincent et les Grenadines"],
    ["BL", "Saint-Bathélemy"],
    ["LC", "Saint-Lucie"],
    ["MF", "Saint-Martin"],
    ["SH", "Sainte Hélène"],
    ["WS", "Samoa"],
    ["AS", "Samoa Américaines"],
    ["ST", "Sao Tomé et Principe"],
    ["SN", "Sénégal"],
    ["RS", "Serbie"],
    ["SC", "Seychelles"],
    ["SL", "Sierra Leone"],
    ["SG", "Singapour"],
    ["SK", "Slovaquie"],
    ["SI", "Slovénie"],
    ["SO", "Somalie"],
    ["SD", "Soudan"],
    ["LK", "Sri Lanka"],
    ["PM", "St. Pierre et Miquelon"],
    ["SE", "Suède"],
    ["CH", "Suisse"],
    ["SR", "Suriname"],
    ["SJ", "Svalbard et Ile Jan Mayen"],
    ["SZ", "Swaziland"],
    ["SY", "Syrie"],
    ["TJ", "Tadjikistan"],
    ["TW", "Taiwan"],
    ["TZ", "Tanzanie"],
    ["TD", "Tchad"],
    ["TF", "Terres Australes Françaises"],
    ["PS", "Territoire Palestinien"],
    ["TH", "Thaïlande"],
    ["TL", "Timor-Leste"],
    ["TG", "Togo"],
    ["TK", "Tokelau"],
    ["TO", "Tonga"],
    ["TT", "Trinité et Tobago"],
    ["TN", "Tunisie"],
    ["TM", "Turkménistan"],
    ["TR", "Turquie"],
    ["TV", "Tuvalu"],
    ["UA", "Ukraine"],
    ["UY", "Uruguay"],
    ["VU", "Vanuatu"],
    ["VA", "Vatican"],
    ["VE", "Vénézuela"],
    ["VN", "Viet Nam"],
    ["WF", "Wallis and Futuna"],
    ["YE", "Yémen"],
    ["ZM", "Zambia"],
    ["ZW", "Zimbabwe"]
]


def create_xml_file():
    if not os.path.exists(PB_PATH):
        os.mkdir(PB_PATH)
    if not os.path.exists(XML_FILE_PATH):
        xmlfile = open(XML_FILE_PATH, 'w')
        xmlfile.write('<PB></PB>')
        xmlfile.close()
